name: Upload website to S3 bucket

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # required to use OIDC authentication
      contents: read # required to checkout the code from the repo
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::916840092047:role/GithubActionsOIDC-Role-M6H2960UCSGC
          role-duration-seconds: 900 # the ttl of the session, in seconds.
          aws-region: eu-west-1 
      - name: Sync files to S3 bucket
        run: |
          aws s3 sync website s3://iankyslytsya.com
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths /*

