permissions:
  id-token: write # required to use OIDC authentication
  contents: read # required to checkout the code from the repo

name: Upload website to S3 bucket

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v2
      - uses: actions/checkout@master
      - uses: jakejarvis/s3-sync-action@master
        with:
          role-to-assume: arn:aws:iam::916840092047:role/GithubActionsOIDC-Role-M6H2960UCSGC
          role-duration-seconds: 900 # the ttl of the session, in seconds.
          aws-region: eu-west-1 # use your region here.
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_REGION: eu-west-1
          SOURCE_DIR: 'website'
